### PR TITLE
Fix links reported by linkcheck

### PR DESCRIPTION
**Pull request by dave-shawley**
This PR does some housekeeping by fixing the broken links as reported by `make linkcheck`.  I noticed that `Python Packaging User Guide` link on https://www.pypa.io/en/latest/history/ was going to a non-existent page on readthedocs.io so I decided that I should fix it.  After shaving a few yaks, this is the result.

### CODE REVIEW

**Comment by lgh2** [comment]
I pulled down the branch and ran `make linkcheck` against it. All the
links in the branch checked as `ok`.

When I was looking at the links more closely, I noticed that in
`source/future.rst`, on line 32, you've changed the link for PEP 426 to
point to PEP 518, but PEP 518 is less explicitly about a metabuild
system and more foundational (specifying minimum build system
requirements). Could you clarify this in the link wording?

**Comment by brainwane** [comment]
Ping, @dave-shawley, regarding @lgh2's [question](https://github.com/pypa/pypa.io/pull/24#issuecomment-360230428). Thanks!

**Comment by brainwane** [comment]
Question for you @dave-shawley -- thanks!

**Comment by brainwane** [comment]
Thanks @dave-shawley!

**Pull request merged**
